# Generated by Django 3.0.3 on 2020-02-28 19:35

import assignment.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_walk', models.NullBooleanField()),
                ('age', models.PositiveIntegerField()),
                ('breed', models.CharField(blank=True, max_length=30)),
                ('trick', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=assignment.models.arrayfield_default_value, size=None)),
                ('email', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DemoModel',
        ),
    ]
