# Generated by Django 3.0.3 on 2020-02-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20200227_0004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='DogOwner',
        ),
    ]
