# Generated by Django 3.0.3 on 2020-02-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20200228_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='trick',
            field=models.CharField(choices=[('SI', 'Sit'), ('FT', 'Fetch'), ('ST', 'Stay'), ('RO', 'Roll Over'), ('NA', 'None. It is okay. My pup was stubborn too.')], default='NA', max_length=2),
        ),
    ]
