# Generated by Django 3.0.3 on 2020-02-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20200227_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='daily_walk',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
