# Generated by Django 3.0.3 on 2020-02-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20200227_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trick',
            name='id',
        ),
        migrations.AlterField(
            model_name='pet',
            name='daily_walk',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='trick',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
