# Generated by Django 3.0.3 on 2020-02-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20200227_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.AddField(
            model_name='pet',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='DogOwner',
        ),
    ]
